-- =============================================================================
-- Site içi bildirim sistemi.
--
-- Her profile için (notifications tablosunda profile_id FK). Bell icon
-- header'da unread count gösterir, dropdown'da son N notification listelenir.
-- =============================================================================

create type notification_type as enum (
  'verification_approved',
  'verification_rejected',
  'warning_received',
  'ban_received',
  'report_received',
  'report_resolved',
  'announcement',
  'system'
);

create table notifications (
  id            bigint generated by default as identity primary key,
  profile_id    uuid not null references profiles(id) on delete cascade,
  type          notification_type not null,
  title         text not null,
  body          text,
  link          text,           -- /uyarilar, /profil/sikayetlerim vb.
  payload       jsonb,          -- ek metadata (report_id, severity, vs.)
  read_at       timestamptz,    -- null ise okunmamış
  created_at    timestamptz not null default now()
);

create index notifications_profile_unread_idx
  on notifications (profile_id, created_at desc)
  where read_at is null;

create index notifications_profile_recent_idx
  on notifications (profile_id, created_at desc);

-- RLS
alter table notifications enable row level security;

-- Kendi notification'larını okuyabilir
create policy "notifications self read" on notifications
  for select using (profile_id = auth.uid());

-- Kendi notification'larını update edebilir (sadece read_at için)
create policy "notifications self update" on notifications
  for update using (profile_id = auth.uid())
  with check (profile_id = auth.uid());

-- Insert sadece service_role tarafından yapılır (server actions üzerinden).
-- Kullanıcının kendisi notification yaratamaz. Bu yüzden insert policy yok.
